addEventHandler("onClientResourceStart", resourceRoot, function()
  engineImportTXD(engineLoadTXD("Forchetta.txd", true), (engineRequestModel("object")))
  engineReplaceModel(engineLoadDFF("Forchetta.dff", 0), (engineRequestModel("object")))
  engineReplaceCOL(engineLoadCOL("Forchetta.col"), (engineRequestModel("object")))
  engineImportTXD(engineLoadTXD("Forchetta2.txd", true), (engineRequestModel("object")))
  engineReplaceModel(engineLoadDFF("Forchetta2.dff", 0), (engineRequestModel("object")))
  engineReplaceCOL(engineLoadCOL("Forchetta2.col"), (engineRequestModel("object")))
  setElementDimension(createObject(engineRequestModel("object"), -794.96, 489.88, 1000, 0, 0, 0), 6802)
  setElementDimension(createObject(engineRequestModel("object"), -794.96, 489.88, 1050, 0, 0, 0), 6802)
  setElementInterior(createObject(engineRequestModel("object"), -794.96, 489.88, 1000, 0, 0, 0), 1)
  setElementInterior(createObject(engineRequestModel("object"), -794.96, 489.88, 1050, 0, 0, 0), 1)
end)
