addEventHandler("onClientResourceStart", resourceRoot, function()
  engineImportTXD(engineLoadTXD("Object1.txd", true), (engineRequestModel("object")))
  engineReplaceModel(engineLoadDFF("Object1.dff", 0), (engineRequestModel("object")))
  engineReplaceCOL(engineLoadCOL("Object1.col"), (engineRequestModel("object")))
  engineSetModelLODDistance(engineRequestModel("object"), 500)
  engineImportTXD(engineLoadTXD("Object2.txd", true), (engineRequestModel("object")))
  engineReplaceModel(engineLoadDFF("Object2.dff", 0), (engineRequestModel("object")))
  engineReplaceCOL(engineLoadCOL("Object2.col"), (engineRequestModel("object")))
  engineImportTXD(engineLoadTXD("Object3.txd", true), (engineRequestModel("object")))
  engineReplaceModel(engineLoadDFF("Object3.dff", 0), (engineRequestModel("object")))
  engineReplaceCOL(engineLoadCOL("Object3.col"), (engineRequestModel("object")))
  engineImportTXD(engineLoadTXD("Object4.txd", true), (engineRequestModel("object")))
  engineReplaceModel(engineLoadDFF("Object4.dff", 0), (engineRequestModel("object")))
  engineReplaceCOL(engineLoadCOL("Object4.col"), (engineRequestModel("object")))
  setElementDimension(createObject(engineRequestModel("object"), 2880.8, 2069.8, 11.6, 0, 0, 0), 9032)
  setElementDimension(createObject(engineRequestModel("object"), 2880.8, 2069.8, 11.6, 0, 0, 0), 9032)
  setElementDimension(createObject(engineRequestModel("object"), 2880.8, 2069.8, 11.6, 0, 0, 0), 9032)
end)
